language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository

script:
  - ./gradlew clean :draweetext:check --no-daemon --stacktrace

notifications:
  email: false

sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/